export enum ShipmentTrackingStatus {
  PENDING = "PENDING",
  IN_TRANSIT = "IN_TRANSIT",
  OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
  DELIVERED = "DELIVERED",
  EXCEPTION = "EXCEPTION",
  UNKNOWN = "UNKNOWN",
}
