export enum OrderStatus {
  PENDING = "PENDING",
  PAID = "PAID",
  IN_PREPARATION = "IN_PREPARATION",
  SHIPPED = "SHIPPED",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
  REFUNDED = "REFUNDED",
}
